workspace:
  base: /go
  path: src/github.com/go-training/training

clone:
  git:
    image: plugins/git:1
    depth: 50
    tags: true

pipeline:
  docker_golang:
    image: plugins/docker:17.12
    secrets: [ docker_username, docker_password ]
    repo: appleboy/golang-http
    dockerfile: example19-deploy-with-kubernetes/Dockerfile
    tags: [ 'latest' ]
    when:
      event: [ push ]
      branch: [ master ]

  prepare:
    image: golang:1.10
    commands:
      - sed -ie "s/THIS_STRING_IS_REPLACED_DURING_BUILD/$(date)/g" example19-deploy-with-kubernetes/deployment.yml
      - cat example19-deploy-with-kubernetes/deployment.yml

  deploy:
    image: sh4d1/drone-kubernetes
    kubernetes_template: example19-deploy-with-kubernetes/deployment.yml
    secrets: [ kubernetes_server, kubernetes_cert, kubernetes_token ]
