apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: gotraining
    tier: frontend
spec:
  type: LoadBalancer
  ports:
    # the port that this service should serve on
  - protocol: TCP
    port: 80
    targetPort: 8080
  selector:
    app: gotraining
    tier: frontend

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: frontend
  # these labels can be applied automatically
  # from the labels in the pod template if not set
  labels:
    app: gotraining
    tier: frontend
spec:
  # this replicas value is default
  # modify it according to your case
  replicas: 3
  # selector can be applied automatically
  # from the labels in the pod template if not set
  # selector:
  #   app: guestbook
  #   tier: frontend
  template:
    metadata:
      labels:
        app: gotraining
        tier: frontend
    spec:
      containers:
      - name: go-hello
        image: appleboy/golang-http
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 8080
